version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: financial_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always


  app:
    build: . 
    depends_on:
      - db 
    env_file:
      - .env 
    restart: on-failure

volumes:
  postgres_data: